<a href="https://colab.research.google.com/github/kapil120/GoogleColab/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Packages


In [0]:
import math

In [10]:
a=math.sqrt(100)
print(a)

10.0


# **Numpy**# 

In [0]:
import numpy as np

In [13]:
x=np.array([1,2,3])
print(x)

[1 2 3]


In [14]:
type(x)

numpy.ndarray

In [15]:
l=[1,4,9,16]
x=np.asarray(l)
type(x)

numpy.ndarray

In [16]:
print(x)

[ 1  4  9 16]


In [18]:
x=np.asarray(l,float)
print(x)

[ 1.  4.  9. 16.]


In [19]:
x.shape

(4,)

In [0]:
np.array?

In [21]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [22]:
x.shape

(2, 3)

In [24]:
x[1,2]

6

In [27]:
x[0,1:3]

array([2, 3])

In [28]:
x=np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
x=np.eye(4,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
x=np.random.random((4,5))
print(x)

[[0.5673002  0.88033618 0.56580192 0.65737114 0.22741317]
 [0.78165189 0.51891697 0.71974108 0.01304877 0.93647854]
 [0.64330095 0.84580654 0.97431145 0.10885092 0.66893755]
 [0.59204696 0.16590474 0.57452359 0.33022795 0.23253637]]


In [31]:
z=x.T
print(z)

[[0.5673002  0.78165189 0.64330095 0.59204696]
 [0.88033618 0.51891697 0.84580654 0.16590474]
 [0.56580192 0.71974108 0.97431145 0.57452359]
 [0.65737114 0.01304877 0.10885092 0.33022795]
 [0.22741317 0.93647854 0.66893755 0.23253637]]


In [32]:
y=x.reshape(20,1)
print(y)

[[0.5673002 ]
 [0.88033618]
 [0.56580192]
 [0.65737114]
 [0.22741317]
 [0.78165189]
 [0.51891697]
 [0.71974108]
 [0.01304877]
 [0.93647854]
 [0.64330095]
 [0.84580654]
 [0.97431145]
 [0.10885092]
 [0.66893755]
 [0.59204696]
 [0.16590474]
 [0.57452359]
 [0.33022795]
 [0.23253637]]


In [33]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [0]:
b=np.arange(5)
c=a+b
d=a-b
e=a*b

In [39]:
print(c,d,e)

[0 2 4 6 8] [0 0 0 0 0] [ 0  1  4  9 16]


In [40]:
#Needs to Understand the concept of Broadcasting In Python
#In this "a" is vector and 1 is scaler

print(a,a+1)

[0 1 2 3 4] [1 2 3 4 5]


In [43]:
a=np.random.random((2,3))
print(a)
print(a+1)

[[0.25105925 0.17096459 0.77404649]
 [0.82110755 0.59292998 0.41276804]]
[[1.25105925 1.17096459 1.77404649]
 [1.82110755 1.59292998 1.41276804]]


In [47]:
#If we wnats to remove the decimal places

a=np.floor(np.random.random((2,3))*15)
print(a)

[[12.  8.  0.]
 [ 5. 12.  1.]]


In [49]:
u=[1,2,3]  #Vector
v=[-1,0,1]

#Inner Product
p1=np.inner(u,v)
print(p1)

2


In [50]:
p2=np.outer(u,v)
print(p2)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]


In [51]:
#Dot Product
a=np.ones((2,3))
b=np.ones((3,2))
np.dot(a,b)

array([[3., 3.],
       [3., 3.]])

In [52]:
#Dot product of transpose of dot a and b

np.dot(b.T,a.T)

array([[3., 3.],
       [3., 3.]])

In [54]:
j=np.ones((2,3))
print(j)

[[1. 1. 1.]
 [1. 1. 1.]]


In [55]:
#To find sum of whole matrix

j.sum()

6.0

In [56]:
#to find sum of columns only

j.sum(axis=0)   #Here 0 means column

array([2., 2., 2.])

In [57]:
#to find sum of rows only

j.sum(axis=1)   #Here 1 means row

array([3., 3.])

In [58]:
#To find maximum value of a matrix

j.max()

1.0