<a href="https://colab.research.google.com/github/kapil120/GoogleColab/blob/master/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Packages


In [0]:
import math

In [10]:
a=math.sqrt(100)
print(a)

10.0


# **Numpy**# 

In [0]:
import numpy as np

In [13]:
x=np.array([1,2,3])
print(x)

[1 2 3]


In [14]:
type(x)

numpy.ndarray

In [15]:
l=[1,4,9,16]
x=np.asarray(l)
type(x)

numpy.ndarray

In [16]:
print(x)

[ 1  4  9 16]


In [18]:
x=np.asarray(l,float)
print(x)

[ 1.  4.  9. 16.]


In [19]:
x.shape

(4,)

In [0]:
np.array?

In [21]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [22]:
x.shape

(2, 3)

In [24]:
x[1,2]

6

In [27]:
x[0,1:3]

array([2, 3])

In [28]:
x=np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
x=np.eye(4,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
x=np.random.random((4,5))
print(x)

[[0.5673002  0.88033618 0.56580192 0.65737114 0.22741317]
 [0.78165189 0.51891697 0.71974108 0.01304877 0.93647854]
 [0.64330095 0.84580654 0.97431145 0.10885092 0.66893755]
 [0.59204696 0.16590474 0.57452359 0.33022795 0.23253637]]
